### ISSUE TITLE
Crashing when making bronze in infusing factory

### ISSUE THREAD

**Issue by rfranceks** [AllTheMods/ATM3-Lite#39]
I am making bronze in an Ultimate Infusing Factory, and there is just two more copper ingots to process, but the world crashed, and now the world crashes on loading. I had the same issue in another world. It crashed mid-processing, it is not like it immediately crashed when the first bronze ingots were made. How can I fix it? Can I keep this world or is it screwed.?
[crash-2019-08-18_14.50.43-server.txt](https://github.com/AllTheMods/ATM3-Lite/files/3513440/crash-2019-08-18_14.50.43-server.txt)

**Comment by Darkere** [comment]
If you are playing alone I'm fairly certain that updating mekanism fixes this bug so that is something you could try. 

Otherwise NBT Explorer or MCedit and remove the machine at this position:
Block location: World: (214,66,247), Chunk: (at 6,4,7 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

**Comment by rfranceks** [comment]
@Darkere I updated the mod pack, which I don't think updated Mekanism but it allowed to me to go into the world now. That particular machine just stopped working now but at least I don't have to start over. Thank you.
